application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  authorization_token: "my-secret-token"
  sender_email: "root@ponbac.xyz"
